name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: ./gradlew test --stacktrace

  apk:
    name: Build apk
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
          
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
